source .venv/bin/activate
set -eu piplefile
#python3 render_and_validate.py files/tst/SetBadLiteralsInLHS.jinja2

python3 render_and_validate.py files/import-resolution/from_import_demo.jinja2
#python3 render_and_validate.py files/trans/BasicTrans_Example_1_3.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_1.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_2.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_3.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_4.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_5.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_6.jinja2
#python3 render_and_validate.py files/trans/BestPractices_Example_14_7.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_10.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_1.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_2.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_3.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_4.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_5.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_6.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_7.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_8.jinja2
#python3 render_and_validate.py files/trans/EdgeCases_Example_13_9.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_1.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_2.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_3.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_4.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_5.jinja2
#python3 render_and_validate.py files/trans/GettextBasic_Example_6_6.jinja2


#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_1.jinja2
#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_2.jinja2
#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_3.jinja2
#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_4.jinja2
#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_5.jinja2
#python3 render_and_validate.py files/trans/GettextNewstyle_Example_11_6.jinja2
#python3 render_and_validate.py files/trans/GettextStandard_Example_10_1.jinja2
#python3 render_and_validate.py files/trans/GettextStandard_Example_10_2.jinja2
#python3 render_and_validate.py files/trans/GettextStandard_Example_10_3.jinja2
#python3 render_and_validate.py files/trans/GettextStandard_Example_10_4.jinja2
#python3 render_and_validate.py files/trans/GettextStandard_Example_10_5.jinja2
#python3 render_and_validate.py files/trans/Ngettext_Example_7_1.jinja2
#python3 render_and_validate.py files/trans/Ngettext_Example_7_2.jinja2
#python3 render_and_validate.py files/trans/Ngettext_Example_7_3.jinja2
#python3 render_and_validate.py files/trans/Ngettext_Example_7_4.jinja2
#python3 render_and_validate.py files/trans/Ngettext_Example_7_5.jinja2
#python3 render_and_validate.py files/trans/Npgettext_Example_9_1.jinja2
#python3 render_and_validate.py files/trans/Npgettext_Example_9_2.jinja2
#python3 render_and_validate.py files/trans/Npgettext_Example_9_3.jinja2
#python3 render_and_validate.py files/trans/Npgettext_Example_9_4.jinja2
#python3 render_and_validate.py files/trans/Pgettext_Example_8_1.jinja2
#python3 render_and_validate.py files/trans/Pgettext_Example_8_2.jinja2
#python3 render_and_validate.py files/trans/Pgettext_Example_8_3.jinja2
#python3 render_and_validate.py files/trans/Pgettext_Example_8_4.jinja2
#python3 render_and_validate.py files/trans/Pgettext_Example_8_5.jinja2


#python3 render_and_validate.py files/trans/RealWorldExamples_Example_12_1.jinja2
#python3 render_and_validate.py files/trans/RealWorldExamples_Example_12_2.jinja2
#python3 render_and_validate.py files/trans/RealWorldExamples_Example_12_3.jinja2
#python3 render_and_validate.py files/trans/RealWorldExamples_Example_12_4.jinja2
#python3 render_and_validate.py files/trans/RealWorldExamples_Example_12_5.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_1.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_2.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_3.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_4.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_5.jinja2
#python3 render_and_validate.py files/trans/TransContext_Example_5_6.jinja2
#python3 render_and_validate.py files/trans/TransPluralization_Example_3_1.jinja2
#python3 render_and_validate.py files/trans/TransPluralization_Example_3_2.jinja2
#python3 render_and_validate.py files/trans/TransPluralization_Example_3_3.jinja2
#python3 render_and_validate.py files/trans/TransPluralization_Example_3_4.jinja2
#python3 render_and_validate.py files/trans/TransPluralization_Example_3_5.jinja2
#python3 render_and_validate.py files/trans/TransVariableBinding_Example_2_1.jinja2
#python3 render_and_validate.py files/trans/TransVariableBinding_Example_2_2.jinja2
#python3 render_and_validate.py files/trans/TransVariableBinding_Example_2_3.jinja2
#python3 render_and_validate.py files/trans/TransVariableBinding_Example_2_4.jinja2
#python3 render_and_validate.py files/trans/TransVariableBinding_Example_2_5.jinja2
#python3 render_and_validate.py files/trans/TransWhitespace_Example_4_1.jinja2
#python3 render_and_validate.py files/trans/TransWhitespace_Example_4_2.jinja2
#python3 render_and_validate.py files/trans/TransWhitespace_Example_4_3.jinja2
#python3 render_and_validate.py files/trans/TransWhitespace_Example_4_4.jinja2